name: Build Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docker_images/**

jobs:
  pushAll:
    name: "docker_image:${{ matrix.game }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        game:
          - garrys-mod-32
          
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./docker_images/${{ matrix.game }}
          file: ./docker_images/${{ matrix.game }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/blazin-gg/pelican-eggs:${{ matrix.game }}